# These are supported funding model platforms

github: amshashank
patreon: amshashank
open_collective: amshashank
ko_fi: amshashank
tidelift: paypal.me/amshashank?locale.x=en_GB
community_bridge: Supporting for Help!
liberapay: amshashank
issuehunt: amshashank
otechie: amshashank
custom: https://paypal.me/amshashank?locale.x=en_GB
